# This is the public configuration file, to override or create some
# values privately just create a private.yml file.  Value in that file
# will be recursively merged with this file.


db: "sqlite:///state.sqlite"
log_level: null
protocols:
  web: 8000
  pb: 8100


# Basic, non-private, slave configuration data.  Basic structure
# of a slave's configuration is:
# <slavename>:
#   type: <linux, mac, windows>
#   python: <list of python versions this host can run>
#   passwd: <password of the agent to communicate with the master>
#
# In addition to the above standard fields, any additional key/value pairs
# will be pass in as keywords to the build slave class.  AWS hosts for example
# have a few extra parameters:
#   http://docs.buildbot.net/0.8.3/reference/buildbot.ec2buildslave.EC2LatentBuildSlave-class.html
slaves:
  persistent:
    deb-7-0:
      enabled: True
      type: linux
      projects:
        core: ["2.6", "2.7", "3.2", "3.3", "3.4"]
        agent: ["2.6", "2.7"]
        master: ["2.7", "3.2", "3.4"]

      passwd: foobar

    osx-mav-0:
      enabled: True
      type: mac
      projects:
        core: ["2.6", "2.7", "3.2", "3.3", "3.4"]
        agent: ["2.6", "2.7"]
        master: ["2.7", "3.2", "3.4"]
      passwd: foobar

  aws:
    win-2012-0:
      enabled: False
      type: windows
      projects:
        core: ["2.6", "2.7", "3.2", "3.3", "3.4"]
        agent: ["2.6", "2.7"]
      passwd: foobar

      # Required
      instance_type: t2.micro
      ami: ami
      identifier: public_key
      secret_identifier: private_key

authz_users: []
authz_perms:
  gracefulShutdown: True
  forceBuild: True
  forceAllBuilds: True
  pingBuilder: True
  stopBuild: True
  stopAllBuilds: True
  cancelPendingBuild: True

changesource:
  user: changeme
  passwd: changeme

  github:
    port: 8200
    secret: foobar
    master: 127.0.0.1:8100
    host: github.com

